import AuthLoader from '@/components/auth/AuthLoader'
import LiquidSideNav from '@/components/ui/liquidSideNav'
import Providers from '@/hooks'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import '../styles/globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        <Providers>
          <AuthLoader />

          <div className='fixed top-3 left-3'>
            <LiquidSideNav />
          </div>

          {children}
        </Providers>
      </body>
    </html>
  )
}
